server {
    listen 443 ssl;
    server_name api.avinest.topoship.com;

    ssl_certificate /etc/letsencrypt/live/api.avinest.topoship.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.avinest.topoship.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://localhost:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


}

server {
    if ($host = api.avinest.topoship.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name api.avinest.topoship.com;
    return 404;
}
