server {
    if ($host = avinest.topoship.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name avinest.topoship.com;
    return 404;
}

server {
    listen 443 ssl;
    server_name avinest.topoship.com;

    ssl_certificate /etc/letsencrypt/live/avinest.topoship.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/avinest.topoship.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Frontend (React later via S3/CloudFront or static)
    location / {
        root /var/www/avinest;
        index index.html;
        try_files $uri /index.html;
    }

    # Backend (Spring Boot)
    location /api/ {
        proxy_pass http://localhost:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}