/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedIndexRouteImport } from './routes/unauthorized/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as StudentLayoutRouteImport } from './routes/student/_layout'
import { Route as FacultyLayoutRouteImport } from './routes/faculty/_layout'
import { Route as StudentLayoutIndexRouteImport } from './routes/student/_layout.index'
import { Route as FacultyLayoutIndexRouteImport } from './routes/faculty/_layout.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedIndexRoute = UnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLayoutRoute = StudentLayoutRouteImport.update({
  id: '/student/_layout',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLayoutRoute = FacultyLayoutRouteImport.update({
  id: '/faculty/_layout',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLayoutIndexRoute = StudentLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLayoutRoute,
} as any)
const FacultyLayoutIndexRoute = FacultyLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyLayoutRouteWithChildren
  '/student': typeof StudentLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/faculty/': typeof FacultyLayoutIndexRoute
  '/student/': typeof StudentLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/faculty': typeof FacultyLayoutIndexRoute
  '/student': typeof StudentLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty/_layout': typeof FacultyLayoutRouteWithChildren
  '/student/_layout': typeof StudentLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/faculty/_layout/': typeof FacultyLayoutIndexRoute
  '/student/_layout/': typeof StudentLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty'
    | '/student'
    | '/login/'
    | '/unauthorized/'
    | '/faculty/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/unauthorized' | '/faculty' | '/student'
  id:
    | '__root__'
    | '/'
    | '/faculty/_layout'
    | '/student/_layout'
    | '/login/'
    | '/unauthorized/'
    | '/faculty/_layout/'
    | '/student/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyLayoutRoute: typeof FacultyLayoutRouteWithChildren
  StudentLayoutRoute: typeof StudentLayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  UnauthorizedIndexRoute: typeof UnauthorizedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized/': {
      id: '/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized/'
      preLoaderRoute: typeof UnauthorizedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/_layout': {
      id: '/student/_layout'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/_layout': {
      id: '/faculty/_layout'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/_layout/': {
      id: '/student/_layout/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentLayoutIndexRouteImport
      parentRoute: typeof StudentLayoutRoute
    }
    '/faculty/_layout/': {
      id: '/faculty/_layout/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyLayoutIndexRouteImport
      parentRoute: typeof FacultyLayoutRoute
    }
  }
}

interface FacultyLayoutRouteChildren {
  FacultyLayoutIndexRoute: typeof FacultyLayoutIndexRoute
}

const FacultyLayoutRouteChildren: FacultyLayoutRouteChildren = {
  FacultyLayoutIndexRoute: FacultyLayoutIndexRoute,
}

const FacultyLayoutRouteWithChildren = FacultyLayoutRoute._addFileChildren(
  FacultyLayoutRouteChildren,
)

interface StudentLayoutRouteChildren {
  StudentLayoutIndexRoute: typeof StudentLayoutIndexRoute
}

const StudentLayoutRouteChildren: StudentLayoutRouteChildren = {
  StudentLayoutIndexRoute: StudentLayoutIndexRoute,
}

const StudentLayoutRouteWithChildren = StudentLayoutRoute._addFileChildren(
  StudentLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyLayoutRoute: FacultyLayoutRouteWithChildren,
  StudentLayoutRoute: StudentLayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  UnauthorizedIndexRoute: UnauthorizedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
