/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedIndexRouteImport } from './routes/unauthorized/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as StudentLayoutRouteImport } from './routes/student/_layout'
import { Route as FacultyLayoutRouteImport } from './routes/faculty/_layout'
import { Route as StudentLayoutIndexRouteImport } from './routes/student/_layout.index'
import { Route as FacultyLayoutIndexRouteImport } from './routes/faculty/_layout.index'
import { Route as StudentLayoutTimetableRouteImport } from './routes/student/_layout.timetable'
import { Route as StudentLayoutProfileRouteImport } from './routes/student/_layout.profile'
import { Route as StudentLayoutMyFacultiesRouteImport } from './routes/student/_layout.my-faculties'
import { Route as FacultyLayoutProfileRouteImport } from './routes/faculty/_layout.profile'
import { Route as FacultyLayoutClassesRouteImport } from './routes/faculty/_layout.classes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedIndexRoute = UnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLayoutRoute = StudentLayoutRouteImport.update({
  id: '/student/_layout',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLayoutRoute = FacultyLayoutRouteImport.update({
  id: '/faculty/_layout',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLayoutIndexRoute = StudentLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentLayoutRoute,
} as any)
const FacultyLayoutIndexRoute = FacultyLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyLayoutRoute,
} as any)
const StudentLayoutTimetableRoute = StudentLayoutTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentLayoutRoute,
} as any)
const StudentLayoutProfileRoute = StudentLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentLayoutRoute,
} as any)
const StudentLayoutMyFacultiesRoute =
  StudentLayoutMyFacultiesRouteImport.update({
    id: '/my-faculties',
    path: '/my-faculties',
    getParentRoute: () => StudentLayoutRoute,
  } as any)
const FacultyLayoutProfileRoute = FacultyLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyLayoutRoute,
} as any)
const FacultyLayoutClassesRoute = FacultyLayoutClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => FacultyLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyLayoutRouteWithChildren
  '/student': typeof StudentLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/faculty/classes': typeof FacultyLayoutClassesRoute
  '/faculty/profile': typeof FacultyLayoutProfileRoute
  '/student/my-faculties': typeof StudentLayoutMyFacultiesRoute
  '/student/profile': typeof StudentLayoutProfileRoute
  '/student/timetable': typeof StudentLayoutTimetableRoute
  '/faculty/': typeof FacultyLayoutIndexRoute
  '/student/': typeof StudentLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/unauthorized': typeof UnauthorizedIndexRoute
  '/faculty/classes': typeof FacultyLayoutClassesRoute
  '/faculty/profile': typeof FacultyLayoutProfileRoute
  '/student/my-faculties': typeof StudentLayoutMyFacultiesRoute
  '/student/profile': typeof StudentLayoutProfileRoute
  '/student/timetable': typeof StudentLayoutTimetableRoute
  '/faculty': typeof FacultyLayoutIndexRoute
  '/student': typeof StudentLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty/_layout': typeof FacultyLayoutRouteWithChildren
  '/student/_layout': typeof StudentLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/unauthorized/': typeof UnauthorizedIndexRoute
  '/faculty/_layout/classes': typeof FacultyLayoutClassesRoute
  '/faculty/_layout/profile': typeof FacultyLayoutProfileRoute
  '/student/_layout/my-faculties': typeof StudentLayoutMyFacultiesRoute
  '/student/_layout/profile': typeof StudentLayoutProfileRoute
  '/student/_layout/timetable': typeof StudentLayoutTimetableRoute
  '/faculty/_layout/': typeof FacultyLayoutIndexRoute
  '/student/_layout/': typeof StudentLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty'
    | '/student'
    | '/login/'
    | '/unauthorized/'
    | '/faculty/classes'
    | '/faculty/profile'
    | '/student/my-faculties'
    | '/student/profile'
    | '/student/timetable'
    | '/faculty/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/faculty/classes'
    | '/faculty/profile'
    | '/student/my-faculties'
    | '/student/profile'
    | '/student/timetable'
    | '/faculty'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/faculty/_layout'
    | '/student/_layout'
    | '/login/'
    | '/unauthorized/'
    | '/faculty/_layout/classes'
    | '/faculty/_layout/profile'
    | '/student/_layout/my-faculties'
    | '/student/_layout/profile'
    | '/student/_layout/timetable'
    | '/faculty/_layout/'
    | '/student/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyLayoutRoute: typeof FacultyLayoutRouteWithChildren
  StudentLayoutRoute: typeof StudentLayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  UnauthorizedIndexRoute: typeof UnauthorizedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized/': {
      id: '/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized/'
      preLoaderRoute: typeof UnauthorizedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/_layout': {
      id: '/student/_layout'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/_layout': {
      id: '/faculty/_layout'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/_layout/': {
      id: '/student/_layout/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentLayoutIndexRouteImport
      parentRoute: typeof StudentLayoutRoute
    }
    '/faculty/_layout/': {
      id: '/faculty/_layout/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyLayoutIndexRouteImport
      parentRoute: typeof FacultyLayoutRoute
    }
    '/student/_layout/timetable': {
      id: '/student/_layout/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentLayoutTimetableRouteImport
      parentRoute: typeof StudentLayoutRoute
    }
    '/student/_layout/profile': {
      id: '/student/_layout/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentLayoutProfileRouteImport
      parentRoute: typeof StudentLayoutRoute
    }
    '/student/_layout/my-faculties': {
      id: '/student/_layout/my-faculties'
      path: '/my-faculties'
      fullPath: '/student/my-faculties'
      preLoaderRoute: typeof StudentLayoutMyFacultiesRouteImport
      parentRoute: typeof StudentLayoutRoute
    }
    '/faculty/_layout/profile': {
      id: '/faculty/_layout/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyLayoutProfileRouteImport
      parentRoute: typeof FacultyLayoutRoute
    }
    '/faculty/_layout/classes': {
      id: '/faculty/_layout/classes'
      path: '/classes'
      fullPath: '/faculty/classes'
      preLoaderRoute: typeof FacultyLayoutClassesRouteImport
      parentRoute: typeof FacultyLayoutRoute
    }
  }
}

interface FacultyLayoutRouteChildren {
  FacultyLayoutClassesRoute: typeof FacultyLayoutClassesRoute
  FacultyLayoutProfileRoute: typeof FacultyLayoutProfileRoute
  FacultyLayoutIndexRoute: typeof FacultyLayoutIndexRoute
}

const FacultyLayoutRouteChildren: FacultyLayoutRouteChildren = {
  FacultyLayoutClassesRoute: FacultyLayoutClassesRoute,
  FacultyLayoutProfileRoute: FacultyLayoutProfileRoute,
  FacultyLayoutIndexRoute: FacultyLayoutIndexRoute,
}

const FacultyLayoutRouteWithChildren = FacultyLayoutRoute._addFileChildren(
  FacultyLayoutRouteChildren,
)

interface StudentLayoutRouteChildren {
  StudentLayoutMyFacultiesRoute: typeof StudentLayoutMyFacultiesRoute
  StudentLayoutProfileRoute: typeof StudentLayoutProfileRoute
  StudentLayoutTimetableRoute: typeof StudentLayoutTimetableRoute
  StudentLayoutIndexRoute: typeof StudentLayoutIndexRoute
}

const StudentLayoutRouteChildren: StudentLayoutRouteChildren = {
  StudentLayoutMyFacultiesRoute: StudentLayoutMyFacultiesRoute,
  StudentLayoutProfileRoute: StudentLayoutProfileRoute,
  StudentLayoutTimetableRoute: StudentLayoutTimetableRoute,
  StudentLayoutIndexRoute: StudentLayoutIndexRoute,
}

const StudentLayoutRouteWithChildren = StudentLayoutRoute._addFileChildren(
  StudentLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyLayoutRoute: FacultyLayoutRouteWithChildren,
  StudentLayoutRoute: StudentLayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  UnauthorizedIndexRoute: UnauthorizedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
